### ISSUE TITLE
Remove JNI header for src/backend/A64/exception_handler_posix.cpp

### ISSUE THREAD

**Issue by Harbyngerr** [citra-emu/dynarmic-android#1]
In the file [src/backend/A64/exception_handler_posix.cpp](https://github.com/citra-emu/dynarmic-android/blob/master/src/backend/A64/exception_handler_posix.cpp), the JNI header causes compilation to fail under a generic aarch64 Linux target.

Is there a particular reason why JNI is needed for this file? Simply surrounding it with an ifdef allowed me to progress further with compilation, but I don't see any code left here where JNI is required.

If it matters at all, I am attempting to compile Citra for an NVidia Jetson Nano.

**Comment by mrcmunir** [comment]
@Harbyngerr Will be Working 
```
#if def(__ANDROID__)
#include "jni.h"
#endif 
```

For now Only Working with Opengl 4.6 driver core .
Don't use gles renderer option Don't have implemented GL_ARM_shader_framebuffer_fetch_depth_stencil
Also no use --fullscreen SDL fullscreen doesn't Working scale very well and Will be broken desktop Screen Resolution.

Prof of concept running on nVIDIA jetson nano with OpenGL renderer  
https://www.youtube.com/watch?v=i4-DugFPgWI

**Comment by xperia64** [comment]
jni.h absolutely does not need to be there. No need for the #ifdef.

**Comment by mrcmunir** [comment]
Ops you're right did not see the entire code  there is no reason to be there jni.h so that header would have to be removed. 
Mrc.

**Comment by SachinVin** [comment]
Removed the header with 6dfd42d.  Thanks for reporting.
